print("Hello world!")
print("Hello again")
print("I like typing like this")
print("This is fun.")
print("Yay! Printing")
print("I'd much rather you 'not'")
# print('I "said" do not touch this.')
#print("I'm supposed to print another line")
#print("This is a new line")